### PR TITLE
Fixed minor issues

### PR DESCRIPTION
**Pull request by ar7bd**
Fixed a few minor issues I found while trying this gem.

### CODE REVIEW

**Comment by Kilobyte22** [comment]
I will check this later. Thanks for the submission

**Comment by Kilobyte22** [comment]
Just looked through the code, looks decent. Got kinda late today though so i can't really do any testing now. Also apparently i was really tired when writing this library.

**Comment by ar7bd** [comment]
No problem. Please take your time. I can provide example code to demonstrate the situations I tried to fix.

**Comment by Kilobyte22** [comment]
I think I should write some specs. Sadly unit-testing network code isn't the easiest. Maybe I'll apply some refactoring though that makes it easier to test.

**Comment by Kilobyte22** [comment]
Sorry, i have completely forgotten about this (mainly because pretty busy IRL), should have time to merge this fairly soon though.

**Comment by ar7bd** [comment]
Don't worry, please take your time.

**Comment by Kilobyte22** [comment]
Finally took some time to review the code, thanks for the contribution... Sadly took way longer than i hoped.

Also bumped the version and pushed it to rubygems so you should get away with using the version from rubygems

**Pull request merged**
